import pygame
from enum import Enum

CONST_GRAVITY = 1000
BLOCK_SIZE = 32
CONST_MAX_VELOCITY = 1000
CONST_JUMP_VELOCITY = 500
CONST_PLAYER_SPEED = 100
CONST_PLAYER_SPRINT_SPEED = 300
CONST_INIT_HEALTH = 100
CONST_INIT_ENERGY = 100
CONST_ENERGY_GAIN_RATE = 25
CONST_SPRINT_ENERGY_RATE = 10

CONST_CAMERA_PLAYER_OFFSET_X = 400
CONST_CAMERA_PLAYER_OFFSET_Y = 200
CONST_SCREEN_HEIGHT = 400
CONST_SCREEN_WIDTH = 800

BLINK_KEY = pygame.K_LCTRL
SPRINT_KEY = pygame.K_LSHIFT

class Facing(Enum):
    LEFT = 0
    RIGHT = 1

