CONST_GRAVITY = 1000
BLOCK_SIZE = 32
CONST_MAX_VELOCITY = 1000
CONST_JUMP_VELOCITY = 500
CONST_PLAYER_SPEED = 100
CONST_PLAYER_SPRINT_SPEED = 250
CONST_MAX_HEALTH = 5
CONST_MAX_ENERGY = 5
CONST_ENERGY_GAIN_RATE = 250
CONST_SPRINT_ENERGY_RATE = 100

CONST_CAMERA_PLAYER_OFFSET_X = 400
CONST_CAMERA_PLAYER_OFFSET_Y = 200

import pygame
BLINK_KEY = pygame.K_LCTRL
